--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- Cities
--========================================================================================================================
		("LOC_CITY_NAME_SUK_GAUL_BIBRACTE",
		"Bibracte"),
		("LOC_CITY_NAME_SUK_GAUL_VIENNE",
		"Vienne"),
		("LOC_CITY_NAME_SUK_GAUL_ALESIA",
		"Alesia"),
		("LOC_CITY_NAME_SUK_GAUL_GERGOVIA",
		"Gergovia"),
		("LOC_CITY_NAME_SUK_GAUL_NEMOSSOS",
		"Nemossos"),
		("LOC_CITY_NAME_SUK_GAUL_LUTETIA",
		"Lutetia"),
		("LOC_CITY_NAME_SUK_GAUL_CENABUM",
		"Cenabum"),
		("LOC_CITY_NAME_SUK_GAUL_DUROCORTORUM",
		"Durocortorum"),
		("LOC_CITY_NAME_SUK_GAUL_LEMONUM",
		"Lemonum"),
		("LOC_CITY_NAME_SUK_GAUL_NAMNETUM",
		"Namnetum"),
		("LOC_CITY_NAME_SUK_GAUL_CONDATE",
		"Condate"),
		("LOC_CITY_NAME_SUK_GAUL_BURDIGALA",
		"Burdigala"),
		("LOC_CITY_NAME_SUK_GAUL_VESONTIO",
		"Vesontio"),
		("LOC_CITY_NAME_SUK_GAUL_ROTOMAGUS",
		"Rotomagus"),
		("LOC_CITY_NAME_SUK_GAUL_SAMAROBRIVA",
		"Samarobriva"),
		("LOC_CITY_NAME_SUK_GAUL_DIVODURUM",
		"Divodurum"),
		("LOC_CITY_NAME_SUK_GAUL_SEGODUNUM",
		"Segodunum"),
		("LOC_CITY_NAME_SUK_GAUL_NEMETOCENNA",
		"Nemetocenna"),
		("LOC_CITY_NAME_SUK_GAUL_AUTRICUM",
		"Autricum"),
		("LOC_CITY_NAME_SUK_GAUL_SUINDINUM",
		"Suindinum"),
		("LOC_CITY_NAME_SUK_GAUL_AVARICON",
		"Avaricon"),
		("LOC_CITY_NAME_SUK_GAUL_DARIORITUM",
		"Darioritum"),
		("LOC_CITY_NAME_SUK_GAUL_AGEDINCUM",
		"Agedincum"),
		("LOC_CITY_NAME_SUK_GAUL_ARGENTORATE",
		"Argentorate"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIOMAGUS",
		"Noviomagus"),
		("LOC_CITY_NAME_SUK_GAUL_BAGACUM",
		"Bagacum"),
		("LOC_CITY_NAME_SUK_GAUL_GESORIACUM",
		"Gesoriacum"),
		("LOC_CITY_NAME_SUK_GAUL_GABILLONUM",
		"Gabillonum"),
		("LOC_CITY_NAME_SUK_GAUL_TOLOSA",
		"Tolosa"),
		("LOC_CITY_NAME_SUK_GAUL_LUGDUNUM",
		"Lugdunum"),
		("LOC_CITY_NAME_SUK_GAUL_UXELLODUNUM",
		"Uxellodunum"),
		("LOC_CITY_NAME_SUK_GAUL_DUROTINCON",
		"Durotincon"),
		("LOC_CITY_NAME_SUK_GAUL_BRATUSPANTION",
		"Bratuspantion"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIODUNUM",
		"Noviodunum"),
		("LOC_CITY_NAME_SUK_GAUL_DIVONA",
		"Divona"),
		("LOC_CITY_NAME_SUK_GAUL_KARNAG",
		"Karnag"),
--========================================================================================================================
-- Citizens
--========================================================================================================================
		("LOC_CITIZEN_SUK_GAUL_MALE_1",
		"Segomāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_2",
		"Brennos"),
		("LOC_CITIZEN_SUK_GAUL_MALE_3",
		"Dubnorīx"),
		("LOC_CITIZEN_SUK_GAUL_MALE_4",
		"Brogimaros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_5",
		"Kintugnātos"),
		("LOC_CITIZEN_SUK_GAUL_MALE_6",
		"Katurīx"),
		("LOC_CITIZEN_SUK_GAUL_MALE_7",
		"Gāromāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_8",
		"Adyantumāros"),
		("LOC_CITIZEN_SUK_GAUL_MALE_9",
		"Albiorix"),
		("LOC_CITIZEN_SUK_GAUL_MALE_10",
		"Wirogalos"),

		("LOC_CITIZEN_SUK_GAUL_FEMALE_1",
		"Dēwognātā"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_2",
		"Kunopennos"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_3",
		"Luguselwā"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_4",
		"Paulla"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_5",
		"Boudilatis"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_6",
		"Rufena"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_7",
		"Severa"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_8",
		"Banona"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_9",
		"Auctiona"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_10",
		"Vlatucia"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_1",
		"Martialis"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_2",
		"Vectitos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_3",
		"Essandecottos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_4",
		"Andareuiseos"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_5",
		"Cerethrius"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_6",
		"Vitalstatistix"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_7",
		"Boduognatus"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_8",
		"Taranis"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_9",
		"Dumnorix"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_10",
		"Lukotorīx"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_1",
		"Andarta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_2",
		"Eskenga"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_3",
		"Rosmerta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_4",
		"Epona"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_5",
		"Sirona"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_6",
		"Arduinna"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_7",
		"Venitouta"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_8",
		"Vlatuca"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_9",
		"Adiega"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_10",
		"Abesa"),
--========================================================================================================================
-- Pedia
--========================================================================================================================
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_GAUL_LOCATION",
		"Europe"),
		("LOC_CIVINFO_SUK_GAUL_SIZE",
		"Est. 191 thousand square miles (494 thousand square km)"),
		("LOC_CIVINFO_SUK_GAUL_POPULATION",
		"Est. 5 million people (at the time of the Roman conquest)"),
		("LOC_CIVINFO_SUK_GAUL_CAPITAL",
		"None (the Gallic tribes were not unified, and each tribe had their own capital)"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_1",
		"In 58 BC, Julius Caesar’s year as consul had come to an end, and he was appointed proconsul of Cisalpine Gaul, a place whose history is a much-debated topic among historians both modern and ancient; a place which some argue did not exist until Caesar’s arrival. Gallic tribes have been in the region referred to as Gaul for as long as historians have recorded the history of the area, and even before."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_2",
		"Gallic culture developed out of the Celtic cultures over the first millennia BC. The Urnfield culture (c. 1300 BC – c. 750 BC) represents the Celts as a distinct cultural branch of the Indo-European-speaking people. The spread of iron working led to the Hallstatt culture in the 8th century BC; the Proto-Celtic (Liguro-Venetic) may have been spoken around this time. The Hallstatt culture evolved into the La Tène culture in around the 5th century BC. The Greek and Etruscan civilizations and colonies began to influence the Gauls especially in the Mediterranean area."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_3",
		"Gallic groups, originating from the various La Tène chiefdoms, began a southeastern movement into the Balkan peninsula from the 4th century BC. Although Celtic settlements were concentrated in the western half of the Carpathian basin, there were notable incursions, and settlements, within the Balkan peninsula itself. From their new bases in northern Illyria and Pannonia, the Gallic invasions climaxed in the early 3rd century BC, with the invasion of Greece. The 279 BC invasion of Greece proper was preceded by a series of other military campaigns waged toward the southern Balkans and against the kingdom of Macedonia, favoured by the state of confusion ensuing from the intricated succession to Alexander. A part of the invasion crossed over to Anatolia and eventually settled in the area that came to be named after them, Galatia."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_4",
		"In 278 BC Gallic settlers in the Balkans were invited by Nicomedes I of Bithynia to help him in a dynastic struggle against his brother. They numbered about 10,000 fighting men and about the same number of women and children, divided into three tribes, Trocmi, Tolistobogii and Tectosages. They were eventually defeated by the Seleucid king Antiochus I (275 BC), in a battle where the Seleucid war elephants shocked the Galatians. While the momentum of the invasion was broken, the Galatians were by no means exterminated and continued to demand tribute from the Hellenistic states of Anatolia to avoid war. 4,000 Galatians were hired as mercenaries by the Ptolemaic Egyptian king Ptolemy II Philadelphus in the 270 BC. According to Pausanias, soon after arrival the Celts plotted “to seize Egypt,” and so Ptolemy marooned them on a deserted island in the Nile River. Galatians also participated at the victorious in 217 BC Battle of Raphia under Ptolemy IV Philopator, and continued to serve as mercenaries for the Ptolemaic Dynasty until its demise in 30 BC. They sided with the renegade Seleucid prince Antiochus Hierax, who reigned in Asia Minor. Hierax tried to defeat king Attalus I of Pergamum (241–197 BC), but instead, the Hellenized cities united under Attalus's banner, and his armies inflicted a severe defeat upon the Galatians at the Battle of the Caecus River in 241 BC. After the defeat, the Galatians continued to be a serious threat to the states of Asia Minor. In fact, they continued to be a threat even after their defeat by Gnaeus Manlius Vulso in the Galatian War (189 BC). Galatia declined and fell at times under Pontic ascendancy. They were finally freed by the Mithridatic Wars, during which they supported Rome. In the settlement of 64 BC, Galatia became a client-state of the Roman empire, the old constitution disappeared, and three chiefs (wrongly styled 'tetrarchs') were appointed, one for each tribe. But this arrangement soon gave way before the ambition of one of these tetrarchs, Deiotarus, the contemporary of Cicero and Julius Caesar, who made himself master of the other two tetrarchies and was finally recognized by the Romans as 'king' of Galatia. The Galatian language continued to be spoken in central Anatolia until the 6th century."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_5",
		"During the Second Punic War the famous Carthaginian general Hannibal Barca utilized Gallic mercenaries in his invasion of Italy. They played a part in some of his most spectacular victories including the battle of Cannae. The Gauls were prosperous enough by the 2nd century that the powerful Greek colony of Massilia had to appeal to the Roman Republic for defense against them. The Romans intervened in southern Gaul in 125 BC, and conquered the area eventually known as Gallia Narbonensis by 121."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_6",
		"The end of the Gauls as an independent people was marked by the Gallic War. It was the conflict in which Julius Caesar first emerged as a great military leader, after an earlier career as an impoverished populist politician. Only after putting down three major Gallic revolts, the last and most famous being led by Vercingetorix, could Caesar claim to have pacified Gaul. Perhaps the most unusual feature of the Gallic War is that in Caesar's commentaries on the war we have a first hand account of all but the last year of the war, written at the time by the most important figure in that war. After this, Gaul became a province of the Roman Empire, and the Gauls were ethnically and culturally largely assimilated into Latin (Roman settlers) majority, losing their tribal identities by the end of the 1st century AD.");
--========================================================================================================================
--========================================================================================================================