INSERT OR REPLACE INTO LocalizedText
		(Tag,									Language,		Text)
VALUES	("LOC_CITY_NAME_MER_COPENHAGEN",		"en_US",		"Copenhagen"),
		("LOC_CITY_NAME_MER_AARHUS",			"en_US",		"Aarhus"),
		("LOC_CITY_NAME_MER_ODENSE",			"en_US",		"Odense"),
		("LOC_CITY_NAME_MER_AALBORG",			"en_US",		"Aalborg"),
		("LOC_CITY_NAME_MER_ROSKILDE",			"en_US",		"Roskilde"),
		("LOC_CITY_NAME_MER_RANDERS",			"en_US",		"Randers"),
		("LOC_CITY_NAME_MER_VIBORG",			"en_US",		"Viborg"),
		("LOC_CITY_NAME_MER_HORSENS",			"en_US",		"Horsens"),
		("LOC_CITY_NAME_MER_HELSINGOR",			"en_US",		"Helsingor"),
		("LOC_CITY_NAME_MER_NYKOBING",			"en_US",		"Nykøbing"),
		("LOC_CITY_NAME_MER_HADERSLEV",			"en_US",		"Haderslev"),
		("LOC_CITY_NAME_MER_RIBE",				"en_US",		"Ribe"),
		("LOC_CITY_NAME_MER_KOLDING",			"en_US",		"Kolding"),
		("LOC_CITY_NAME_MER_VEJLE",				"en_US",		"Vejle"),
		("LOC_CITY_NAME_MER_SVENDBORG",			"en_US",		"Svendborg"),
		("LOC_CITY_NAME_MER_NAESTVED",			"en_US",		"Næstved"),
		("LOC_CITY_NAME_MER_AABENRAA",			"en_US",		"Aabenraa"),
		("LOC_CITY_NAME_MER_VARDE",				"en_US",		"Varde"),
		("LOC_CITY_NAME_MER_HJORRING",			"en_US",		"Hjørring"),
		("LOC_CITY_NAME_MER_SLAGELSE",			"en_US",		"Slagelse"),
		("LOC_CITY_NAME_MER_RINGSTED",			"en_US",		"Ringsted"),
		("LOC_CITY_NAME_MER_ESBJERG",			"en_US",		"Esbjerg"),
		("LOC_CITY_NAME_MER_FREDERICIA",		"en_US",		"Fredericia"),
		("LOC_CITY_NAME_MER_HORSHOLM",			"en_US",		"Hørsholm"),
		("LOC_CITY_NAME_MER_HERNING",			"en_US",		"Herning"),
		("LOC_CITY_NAME_MER_FREDERIKSHAVN",		"en_US",		"Frederikshavn"),
		("LOC_CITY_NAME_MER_HOLBAEK",			"en_US",		"Holbæk"),
		("LOC_CITY_NAME_MER_NYBORG",			"en_US",		"Nyborg"),
		("LOC_CITY_NAME_MER_SONDERBORG",		"en_US",		"Sønderborg"),
		("LOC_CITY_NAME_MER_KOGE",				"en_US",		"Køge"),
		("LOC_CITY_NAME_MER_SILKEBORG",			"en_US",		"Silkeborg"),
		("LOC_CITY_NAME_MER_HILLEROD",			"en_US",		"Hillerød"),
		("LOC_CITY_NAME_MER_SKANDERBORG",		"en_US",		"Skanderborg"),
		("LOC_CITY_NAME_MER_NAKSKOV",			"en_US",		"Nakskov"),
		("LOC_CITY_NAME_MER_RONNE",				"en_US",		"Rønne");

