/*
	Leader Unique Ability
	Authors: MC
*/

-----------------------------------------------
-- Types
-----------------------------------------------

INSERT INTO	Types
		(Type,												Kind			)
VALUES	('TRAIT_LEADER_CYH_GLORIOUS_RIDE',			'KIND_TRAIT'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',			'KIND_ABILITY'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH',			'KIND_ABILITY'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS',			'KIND_ABILITY'),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF',			'KIND_ABILITY'),
		('ABILITY_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',			'KIND_ABILITY'),
		('ABILITY_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',			'KIND_ABILITY');

-----------------------------------------------
-- Tags
-----------------------------------------------

-----------------------------------------------
-- TypeTags
-----------------------------------------------

-----------------------------------------------
-- UnitAbilities
-----------------------------------------------

INSERT INTO UnitAbilities
		(UnitAbilityType,									Name,												Description,												Inactive	)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',	'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_COMBAT_NAME',	'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_COMBAT_DESCRIPTION',		1			),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH',	NULL,	NULL,		1			),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS',	NULL,	NULL,		1			),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF',	NULL,	NULL,		1			);

INSERT INTO RequirementSets
		(RequirementSetId,							RequirementSetType)
VALUES	('REQUIREMENT_SET_UNIT_DEFENDING_ON_HILLS',						'REQUIREMENTSET_TEST_ALL'),
		('REQUIREMENT_SET_UNIT_DEFENDING_ON_REEF',						'REQUIREMENTSET_TEST_ALL'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_FLOODPLAINS',						'REQUIREMENTSET_TEST_ALL'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_MARSH',						'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements
		(RequirementSetId,					RequirementId)
VALUES	('REQUIREMENT_SET_UNIT_DEFENDING_ON_HILLS',				'PLOT_IS_HILLS_REQUIREMENT'),
		('REQUIREMENT_SET_UNIT_DEFENDING_ON_HILLS',		'PLAYER_IS_DEFENDER_REQUIREMENTS'),
		('REQUIREMENT_SET_UNIT_DEFENDING_ON_REEF',				'REQUIRES_PLOT_HAS_REEF'),
		('REQUIREMENT_SET_UNIT_DEFENDING_ON_REEF',		'PLAYER_IS_DEFENDER_REQUIREMENTS'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_FLOODPLAINS',				'REQUIRES_PLOT_HAS_FLOODPLAINS_TAG'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_FLOODPLAINS',		'PLAYER_IS_ATTACKER_REQUIREMENTS'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_MARSH',				'PLOT_IS_MARSH_REQUIREMENT'),
		('REQUIREMENT_SET_UNIT_ATTACKING_ON_MARSH',		'PLAYER_IS_ATTACKER_REQUIREMENTS');

-----------------------------------------------
-- UnitAbilityModifiers
-----------------------------------------------

INSERT INTO UnitAbilityModifiers
		(UnitAbilityType,									ModifierId							)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',	'ATTACK_BONUS_ON_FLOODPLAINS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH',	'ATTACK_BONUS_ON_MARSH'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS',	'DEFENSE_BONUS_ON_HILLS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF',	'DEFENSE_BONUS_ON_REEF'	); 

INSERT INTO TypeTags
		(Type,						Tag						)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',		'CLASS_ALL_COMBAT_UNITS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',		'CLASS_RELIGIOUS_ALL'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH',		'CLASS_ALL_COMBAT_UNITS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH',		'CLASS_RELIGIOUS_ALL'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS',		'CLASS_ALL_COMBAT_UNITS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS',		'CLASS_RELIGIOUS_ALL'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF',		'CLASS_ALL_COMBAT_UNITS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF',		'CLASS_RELIGIOUS_ALL'	);

INSERT INTO Modifiers	
		(ModifierId,									ModifierType,		SubjectRequirementSetId		)
VALUES	('ATTACK_BONUS_ON_FLOODPLAINS',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',	'REQUIREMENT_SET_UNIT_ATTACKING_ON_FLOODPLAINS'		),
		('ATTACK_BONUS_ON_MARSH',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',		'REQUIREMENT_SET_UNIT_ATTACKING_ON_MARSH'		),
		('DEFENSE_BONUS_ON_HILLS',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',		'REQUIREMENT_SET_UNIT_DEFENDING_ON_HILLS'		),
		('DEFENSE_BONUS_ON_REEF',		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',		'REQUIREMENT_SET_UNIT_DEFENDING_ON_REEF'		);

INSERT INTO ModifierArguments		
		(ModifierId,										Name,						Value	)
VALUES	--('ATTACK_BONUS_ON_UNFAVORABLE_TERRAIN',			'Amount',					5		),
		--('DEFENSE_BONUS_ON_FAVORABLE_TERRAIN',			'Amount',					3		);
		('ATTACK_BONUS_ON_FLOODPLAINS',			'Amount',					5		),
		('ATTACK_BONUS_ON_MARSH',			'Amount',					5		),
		('DEFENSE_BONUS_ON_HILLS',			'Amount',					3		),
		('DEFENSE_BONUS_ON_REEF',			'Amount',					3		);

-----------------------------------------------
-- Traits
-----------------------------------------------

INSERT INTO	Traits
		(TraitType,									Name,												Description												)
VALUES	('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_NAME',	'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_DESCRIPTION'	);
		
-----------------------------------------------
-- LeaderTraits
-----------------------------------------------

INSERT INTO	LeaderTraits
		(LeaderType,			TraitType								)
VALUES	('LEADER_CYH_JAN_ZIZKA',	'TRAIT_LEADER_CYH_GLORIOUS_RIDE'	);

-----------------------------------------------
-- Modifiers
-----------------------------------------------

INSERT INTO Modifiers
		(ModifierId,											ModifierType,								Permanent	)
VALUES	('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_MARSH',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_HILLS',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_REEF',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			);

-----------------------------------------------
-- TraitModifiers
-----------------------------------------------

INSERT INTO TraitModifiers 
		(TraitType,									ModifierId											)
VALUES	('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_FLOODPLAINS'	),
		('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_MARSH'	),
		('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_HILLS'	),
		('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_REEF'	);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

INSERT INTO ModifierArguments 
		(ModifierId,										Name,				Value												)
VALUES	('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_FLOODPLAINS',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS'	),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_ATTACK_MARSH',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_ATTACK_MARSH'	),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_HILLS',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_DEFEND_HILLS'	),
		('TRAIT_GRANT_UNITS_GLORIOUS_RIDE_DEFEND_REEF',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_DEFEND_REEF'	);

INSERT INTO ModifierStrings
		(ModifierId,									Context,		Text							)
VALUES	('ATTACK_BONUS_ON_FLOODPLAINS',		'Preview',		'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_ATTACK_FLOODPLAINS_DESCRIPTION'		),
		('ATTACK_BONUS_ON_MARSH',		'Preview',		'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_ATTACK_MARSH_DESCRIPTION'		),
		('DEFENSE_BONUS_ON_HILLS',		'Preview',		'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_DEFEND_HILLS_DESCRIPTION'		),
		('DEFENSE_BONUS_ON_REEF',		'Preview',		'LOC_TRAIT_LEADER_CYH_GLORIOUS_RIDE_DEFEND_REEF_DESCRIPTION'		);

--------

INSERT INTO TraitModifiers 
		(TraitType,									ModifierId											)
VALUES	('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_RELIGIOUS_UNITS_GREAT_GENERAL_POINTS'	),
		('TRAIT_LEADER_CYH_GLORIOUS_RIDE',	'TRAIT_GRANT_MILITARY_UNITS_GREAT_PROPHET_POINTS'	);

INSERT INTO Modifiers
		(ModifierId,											ModifierType,								Permanent	)
VALUES	('TRAIT_GRANT_RELIGIOUS_UNITS_GREAT_GENERAL_POINTS',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			),
		('TRAIT_GRANT_MILITARY_UNITS_GREAT_PROPHET_POINTS',		'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',		1			);

INSERT INTO ModifierArguments 
		(ModifierId,										Name,				Value												)
VALUES	('TRAIT_GRANT_RELIGIOUS_UNITS_GREAT_GENERAL_POINTS',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS'	),
		('TRAIT_GRANT_MILITARY_UNITS_GREAT_PROPHET_POINTS',	'AbilityType',		'ABILITY_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS'	);

INSERT INTO UnitAbilities
		(UnitAbilityType,									Name,												Description,												Inactive	)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',	NULL,	NULL,		1			),
		('ABILITY_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',	NULL,	NULL,		1			);

INSERT INTO Modifiers
		(ModifierId,											ModifierType,								Permanent	)
VALUES	('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',		'MODIFIER_PLAYER_UNIT_ADJUST_GREAT_PEOPLE_POINTS_PER_KILL',		1			),
		('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',		'MODIFIER_PLAYER_UNIT_ADJUST_GREAT_PEOPLE_POINTS_PER_KILL',		1			);


INSERT INTO UnitAbilityModifiers
		(UnitAbilityType,									ModifierId							)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',	'MODIFIER_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',	'MODIFIER_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS'	); 

INSERT INTO TypeTags
		(Type,						Tag						)
VALUES	('ABILITY_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',		'CLASS_ALL_COMBAT_UNITS'	),
		('ABILITY_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',		'CLASS_RELIGIOUS_ALL'	);

INSERT INTO ModifierArguments 
		(ModifierId,										Name,		Type,				Value												)
VALUES	('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',	'GreatPersonClassType',		'ARGTYPE_IDENTITY',		'GREAT_PERSON_CLASS_GENERAL'	),
		('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',	'GreatPersonClassType',		'ARGTYPE_IDENTITY',		'GREAT_PERSON_CLASS_PROPHET'	),
		('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_GENERAL_POINTS',	'Amount',		'ARGTYPE_IDENTITY',		3	),
		('MODIFIER_CYH_GLORIOUS_RIDE_GREAT_PROPHET_POINTS',	'Amount',		'ARGTYPE_IDENTITY',		3	);